# firmware/assets/captive-portal/gen_form_html.py
"""Generate a per-kid PROGMEM C++ header from form.html.template + form.css.

Usage:
    # Build-time (PlatformIO extra_script)
    python gen_form_html.py --kid emory --out /path/to/form_html.h

    # Local browser preview (substitutes tokens, prints to stdout)
    python gen_form_html.py --kid emory --preview > /tmp/preview.html
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
ASSETS = Path(__file__).resolve().parent
TEMPLATE = ASSETS / "form.html.template"
CSS = ASSETS / "form.css"

# TZ options must stay in lockstep with firmware/lib/wifi_provision/src/tz_options.cpp
TZ_OPTIONS = [
    ("Pacific (Los Angeles, Seattle)",       "PST8PDT,M3.2.0,M11.1.0"),
    ("Mountain (Denver, Salt Lake City)",    "MST7MDT,M3.2.0,M11.1.0"),
    ("Arizona (Phoenix, no DST)",            "MST7"),
    ("Central (Chicago, Dallas)",            "CST6CDT,M3.2.0,M11.1.0"),
    ("Eastern (New York, Miami)",            "EST5EDT,M3.2.0,M11.1.0"),
    ("Alaska (Anchorage)",                   "AKST9AKDT,M3.2.0,M11.1.0"),
    ("Hawaii (Honolulu)",                    "HST10"),
    ("UTC",                                  "UTC0"),
]

PACIFIC_POSIX = TZ_OPTIONS[0][1]

KID_TOKENS = {
    "emory": {
        "KID_NAME": "Emory",
        "KID_ACCENT_COLOR": "#b88b4a",
        "KID_BG_COLOR":     "#dcc09a",
    },
    "nora": {
        "KID_NAME": "Nora",
        "KID_ACCENT_COLOR": "#3d2817",
        "KID_BG_COLOR":     "#f0e0c0",
    },
}


def render_tz_options() -> str:
    parts = []
    for label, posix in TZ_OPTIONS:
        sel = " selected" if posix == PACIFIC_POSIX else ""
        parts.append(f'<option value="{posix}"{sel}>{label}</option>')
    return "\n        ".join(parts)


def substitute(template: str, kid: str, *, csrf_placeholder: str, error_placeholder: str) -> str:
    css = CSS.read_text()
    tokens = dict(KID_TOKENS[kid])
    # CSS has its own tokens; substitute those first, then inline.
    for k, v in tokens.items():
        css = css.replace("{{" + k + "}}", v)
    out = template
    for k, v in tokens.items():
        out = out.replace("{{" + k + "}}", v)
    out = out.replace("{{INLINE_CSS}}", css)
    out = out.replace("{{TZ_OPTIONS}}", render_tz_options())
    out = out.replace("{{CSRF_TOKEN}}", csrf_placeholder)
    out = out.replace("{{ERROR_MESSAGE}}", error_placeholder)
    return out


def to_c_string_literal(html: str) -> str:
    # Escape for a C++ raw string literal. We use a raw string with a custom
    # delimiter to avoid fussy backslash handling in HTML/JS.
    delim = "WCHTML"
    if f"){delim}" in html:
        raise RuntimeError(f"HTML contains the raw-string delimiter {delim}; pick another")
    return f'const char FORM_HTML[] PROGMEM = R"{delim}({html}){delim}";\n'


def _collapse_newlines(html: str) -> str:
    # Collapse to a single line so the embedded raw string literal contains no
    # real newlines. This keeps the generated header compact and sidesteps any
    # tooling that chokes on multi-line raw strings.
    return " ".join(line.strip() for line in html.splitlines() if line.strip())


def emit_header(kid: str, out_path: Path) -> None:
    template = TEMPLATE.read_text()
    # CSRF and error are runtime-substituted on the ESP32, not at build time.
    # The build embeds the literal tokens; the web server replaces them per request.
    html = substitute(template, kid,
                      csrf_placeholder="{{CSRF_TOKEN}}",
                      error_placeholder="{{ERROR_MESSAGE}}")
    html = _collapse_newlines(html)
    header = (
        "// Generated by gen_form_html.py — do not edit.\n"
        "#pragma once\n\n"
        + to_c_string_literal(html)
    )
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(header)


def emit_preview(kid: str) -> str:
    template = TEMPLATE.read_text()
    # Preview has no real CSRF / error, and injects a mock /scan stub so the
    # dropdown shows something without an ESP32.
    html = substitute(template, kid,
                      csrf_placeholder="preview-csrf",
                      error_placeholder="")
    mock = """
    <script>
      window.fetch = async () => ({ json: async () => ([
          {ssid: 'HomeWiFi-5G', rssi: -45, secured: true},
          {ssid: 'HomeWiFi-2.4', rssi: -52, secured: true},
          {ssid: 'Neighbor', rssi: -70, secured: true},
          {ssid: 'Guest', rssi: -60, secured: false},
      ])});
    </script>
    """
    return html.replace("</body>", mock + "</body>")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--kid", required=True, choices=list(KID_TOKENS))
    ap.add_argument("--preview", action="store_true",
                    help="Write browser-previewable HTML to stdout.")
    ap.add_argument("--out", type=Path,
                    help="Path to write the embedded C++ header (required when not --preview).")
    args = ap.parse_args()

    if args.preview:
        sys.stdout.write(emit_preview(args.kid))
        return 0

    if not args.out:
        print("--out is required when not in --preview mode", file=sys.stderr)
        return 2

    emit_header(args.kid, args.out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
