"""Light channel — production part for the word clock.

Single-piece honeycomb that sits on top of the PCB, with one pocket per
word (multi-cell; 1-3 LEDs per word on the 63-LED board, long words
light several adjacent LEDs) and one pocket per filler cell
(single-cell, no LED — stays dark behind the corresponding face letter).
Walls are 2 mm thick black PLA, 17.84 mm tall — extend from PCB top to
the diffusion film bonded on the back of the face.

Pin handling (v4, 2026-07-05 — first-principles rework after coupon
dry-fits): every through-hole component's pins protrude ≤4 mm on the
LED side of the PCB, and ~100 of the 146 THT pads land under the
channel's wall lines — a flat-bottomed channel rides up on the stubs.
Design principle: the original honeycomb was pure void (maximum light),
so pin handling must add essentially nothing. Two mechanisms, both
subtractive-first:

  RELIEF CAVITY (pure void) — every pad gets a blind cavity
  (CAVITY_DEPTH_MM deep, pad + CAVITY_MARGIN_MM). Each daughtercard
  header row (HEADER_ROWS) gets one merged slot cavity instead
  (bent-flat socket tails spread solder along the row, so per-pin
  squares are the wrong shape). A cavity that only bites partway into
  a wall leaves ≥ MIN_WALL_SKIN_MM skin — a light-tight dent.

  WALL JOG — where a cavity would eat clear through a wall, the wall
  routes AROUND the relief: a 2 mm rib, only JOG_HEIGHT_MM tall,
  detours on the clear side (chosen per site to clear every LED
  package and every relief) and closes back with two end stubs. Above
  the jog the original straight wall is untouched, so from the
  letters' perspective the lattice is unchanged except thin low ribs
  near the PCB. Where neither side works (a pin row crossing a wall
  mid-column — a fence no wall can route around), the crossing is
  CLOSED by a BRIDGE block: legs drop to the PCB in the clear strips
  flanking the pin line and a roof spans over the pins. No open notch
  remains in any wall face.

Cavities through the 1 mm envelope-edge skin leak only into the frame
gap, where the walnut absorbs it; there is no letter-to-letter path.
Pad positions come from hardware/word-clock-tht-pads.csv (incl. NPTH
mounting holes at screw-head size) and LED positions from
hardware/word-clock-led-pos.csv, both regenerated by export_tht_pads.py.

Per-kid: NAME pocket length differs (Emory 5 cells, Nora 4 cells); pass
--target.

Stack-up reference (CORRECTED 2026-07-09 — the cavity is the full 48.0;
face and panel live OUTSIDE it; z = 0 at the panel's interior surface):
    face back / film top      z = 48.00
    diffusion film   0.16 mm  (z = 47.84 to 48.00; bonded to face back)
    light channel   17.84 mm  (z = 30.00 to 47.84; top edge seals to film)
    PCB              1.60 mm  (z = 28.40 to 30.00; LEDs on top side)
    carrier posts   25.90 mm  (z =  2.50 to 28.40)
    carrier web      2.50 mm  (z =  0.00 to  2.50; glued to panel interior)

Outer envelope = 13 × CELL_PITCH_MM = 177.8 mm, matching the face
SVG's letter-grid extent (`enclosure/scripts/render_face.py:GRID_SIZE_MM`
divided by 13). The OUTER cells have no thick outer wall — the FRAME
wall (6.4 mm walnut/maple) right next to the channel does the outer
light blocking instead. This keeps the channel compact and avoids
fighting the frame interior dimension for that last 1-2 mm of
perimeter.

Alignment note (verified 2026-04-26 via truth-verifier review against
`hardware/word-clock-all-pos.csv`): the channel pitch (13.6769 mm =
177.8 / 13) matches the face SVG, NOT the PCB's actual LED-grid pitch
(13.68 mm = ~177.84 mm extent, derived from the LED CSV). PCB also has
its LED grid offset by approximately (-1.5 mm, +0.5 mm) from PCB
outline origin. The two are 0.04 mm out of sync end-to-end, plus a
1.5 mm origin offset. We deliberately align this script to the FACE
because that's the visible alignment surface — channel walls land at
face cell boundaries, ensuring inter-letter light isolation. The
consequence is LEDs sit ~1.5 mm off-center within their word pockets;
with 11.68 mm pocket interior vs 5 mm LED package, that's 3.34 mm of
clearance to the nearest wall — invisible at typical viewing distance.

The diffuser stack is now film-only (acrylic dropped 2026-04-26 after
bench test showed it caused 5 mm of lateral light bleed). If first-light
testing reveals visible hot spots through the film, the recovery is to
cut acrylic into per-pocket pieces and reprint this script with
WALL_HEIGHT_MM bumped to ~21 mm (so walls extend through the acrylic
level, isolating each pocket optically).

Run from repo root:
    enclosure/3d/.venv/bin/python enclosure/3d/light_channel.py --target emory
    enclosure/3d/.venv/bin/python enclosure/3d/light_channel.py --target nora

Output: enclosure/3d/out/light_channel_{target}.stl

Print: black PLA or black PETG — opacity is the mandatory property
(light blocking between pockets); PETG is preferred for the final part
(better creep resistance under the compression sandwich's sustained
preload and higher softening temperature inside the warm enclosure).
Open ends up so all pockets vent properly. ~6-8 hours at default A1
speeds. Brim recommended since the bottom face is mostly negative space
(just wall edges in contact with the bed). Print PCB-side DOWN, exactly
as the STL loads — do NOT flip it in the slicer (that mirrors the part
relative to the board). The relief cavities start at the bed; the small
bridges they create in wall bases print fine without support. Supports
must stay OFF. Place on the board with the chamfered corner at the
board's D1 (IT-IS) corner.
"""
import argparse
import csv
from build123d import (Align, Box, Compound, Plane, Pos, Rot, ShapeList,
                       export_stl, mirror)
from pathlib import Path

# ─── Locked parameters ──────────────────────────────────────────
GRID_SIZE_MM        = 177.8                  # matches face GRID_SIZE_MM
                                             # and PCB outline 177.8 × 177.8
CELL_PITCH_MM       = GRID_SIZE_MM / 13      # ≈ 13.6769 mm
WALL_THICKNESS_MM   = 2.0
WALL_HEIGHT_MM      = 17.84                  # PCB top → film bottom

# Pin shrouds over through-hole pad stubs (see docstring).
CAVITY_DEPTH_MM     = 5.0                    # measured protrusions <4 mm
CAVITY_MARGIN_MM    = 1.2                    # per side, beyond the pad edge
SLOT_MARGINS_MM     = {"J_RTC1": 6.0,       # bent-flat tails reach 4-6 mm
                       "J_SD1": 6.0,         # same treatment: its h3 wall
                                             # crossing is closed by a BRIDGE
                                             # (a jog can't fit between
                                             # D8 and D40, a bridge can)
                       "J_AMP1": 6.0}        # uniform
JOG_HEIGHT_MM       = CAVITY_DEPTH_MM + 1.0  # jogged wall ribs: only as tall
                                             # as the pins they route around;
                                             # the straight wall continues
                                             # untouched above
BRIDGE_LEG_MM       = 0.8                    # bridge legs in the clear strips
BRIDGE_CLEAR_MM     = 4.5                    # roof underside; pins are <4 mm
BRIDGE_TOP_MM       = 6.4                    # bridge block total height
BRIDGE_OVERHANG_MM  = 2.0                    # bridge extends past the wall band
LETTER_HALF_MM      = 4.1                    # letters occupy the central
                                             # ~8.2 mm of a cell (soft limit
                                             # for jog placement)
HEADER_ROWS         = ("J_RTC1", "J_SD1", "J_AMP1")
MIN_WALL_SKIN_MM    = 0.5                    # thinnest acceptable dent skin
LED_HALF_MM         = 2.5                    # WS2812B 5050 package half-width
LED_MIN_GAP_MM      = 0.25                   # required shroud-to-LED air gap
_HW = Path(__file__).resolve().parents[2] / "hardware"
THT_PADS_CSV        = _HW / "word-clock-tht-pads.csv"
LED_POS_CSV         = _HW / "word-clock-led-pos.csv"

# ─── Word spans (mirror grid.cpp set_spans_common) ──────────────
# Each entry: (row, col, length). One LED per word at word center.
# Order doesn't matter for the geometry — set semantics on word_cells.
WORD_SPANS = [
    # row 0: I T  E  I S  M  T E N  H A L F
    (0, 0, 2),    # IT
    (0, 3, 2),    # IS
    (0, 6, 3),    # TEN_MIN
    (0, 9, 4),    # HALF
    # row 1: Q U A R T E R  T W E N T Y
    (1, 0, 7),    # QUARTER
    (1, 7, 6),    # TWENTY
    # row 2: F I V E  O  M I N U T E S  R
    (2, 0, 4),    # FIVE_MIN
    (2, 5, 7),    # MINUTES
    # row 3: Y  H A P P Y  P A S T  T O  1
    (3, 1, 5),    # HAPPY
    (3, 6, 4),    # PAST
    (3, 10, 2),   # TO
    # row 4: O N E  B I R T H  T H R E E
    (4, 0, 3),    # ONE
    (4, 3, 5),    # BIRTH
    (4, 8, 5),    # THREE
    # row 5: E L E V E N  F O U R  D A Y
    (5, 0, 6),    # ELEVEN
    (5, 6, 4),    # FOUR
    (5, 10, 3),   # DAY
    # row 6: T W O  E I G H T  S E V E N
    (6, 0, 3),    # TWO
    (6, 3, 5),    # EIGHT
    (6, 8, 5),    # SEVEN
    # row 7: N I N E  S I X  T W E L V E
    (7, 0, 4),    # NINE
    (7, 4, 3),    # SIX
    (7, 7, 6),    # TWELVE
    # row 8: <NAME>  0  A  T  F I V E  6   (NAME added per-kid below)
    #   - Cells 5 ('0'/'1') and 12 ('6'/'9') are filler letters per kid.
    #   - Cells 6-7 ('A','T') are decorative-only — the actual AT word
    #     span is on row 11 (cols 10-11). These two cells become
    #     1-cell filler pockets here, matching grid.cpp's intent
    #     (set_spans_common doesn't register them).
    (8, 8, 4),    # FIVE_HR
    # row 9: T E N  O C L O C K  N O O N
    (9, 0, 3),    # TEN_HR
    (9, 3, 6),    # OCLOCK
    (9, 9, 4),    # NOON
    # row 10: 2  I N  T H E  M O R N I N G
    (10, 1, 2),   # IN
    (10, 3, 3),   # THE
    (10, 6, 7),   # MORNING
    # row 11: A F T E R N O O N  0  A T  2
    (11, 0, 9),   # AFTERNOON
    (11, 10, 2),  # AT
    # row 12: E V E N I N G  3  N I G H T
    (12, 0, 7),   # EVENING
    (12, 8, 5),   # NIGHT
]

# NAME varies per-kid (length differs). Always at row 8 col 0.
NAME_SPANS = {
    "emory": (8, 0, 5),  # E M O R Y
    "nora":  (8, 0, 4),  # N O R A
}



def _fuse(shape):
    """Boolean ops on a ShapeList are list ops, not geometry ops — coerce
    multi-body results back to a Compound so subsequent booleans behave."""
    if isinstance(shape, ShapeList):
        return Compound(list(shape))
    return shape


def build_channel(target: str) -> tuple[Compound, int, int]:
    """Construct the channel as outer-envelope minus all pockets.

    Returns (channel_compound, n_word_pockets, n_filler_pockets). The
    target validation is here (in addition to argparse choices=) so this
    function is safe to call directly from tests or other scripts
    without going through the CLI.
    """
    if target not in NAME_SPANS:
        raise ValueError(f"unknown target: {target!r} (expected emory or nora)")

    # All word pockets for this target (NAME varies)
    spans = WORD_SPANS + [NAME_SPANS[target]]

    # Cells covered by some word — used to derive filler cells.
    # Also catches overlapping spans (would surface as |word_cells| < sum of lengths).
    word_cells = set()
    for row, col, length in spans:
        for c in range(col, col + length):
            word_cells.add((row, c))
    total_word_lengths = sum(length for _, _, length in spans)
    assert len(word_cells) == total_word_lengths, (
        f"WORD_SPANS contain overlapping cells: "
        f"unique cells {len(word_cells)} != sum of lengths {total_word_lengths}"
    )

    # Filler cells = grid cells NOT in any word. Each gets a 1-cell pocket.
    filler_cells = [
        (row, col)
        for row in range(13)
        for col in range(13)
        if (row, col) not in word_cells
    ]
    # Every cell in the 13×13 grid must be covered by exactly one pocket
    # (word or filler). Catches drift between WORD_SPANS and grid.cpp.
    assert len(word_cells) + len(filler_cells) == 13 * 13, (
        f"cells not fully covered: "
        f"{len(word_cells)} word + {len(filler_cells)} filler != {13 * 13}"
    )

    BOTTOM = (Align.MIN, Align.MIN, Align.MIN)
    half_wall = WALL_THICKNESS_MM / 2

    # Outer envelope = grid extent. Outer cells touch the envelope
    # boundary; outer light blocking comes from the frame wood, not from
    # a thick perimeter wall on the channel itself.
    channel = Box(GRID_SIZE_MM, GRID_SIZE_MM, WALL_HEIGHT_MM, align=BOTTOM)

    # Subtract a pocket for each word. Pocket extends from
    # (col*pitch + half_wall) to ((col+length)*pitch − half_wall) so
    # adjacent pockets share a 2 mm wall.
    for row, col, length in spans:
        x = col * CELL_PITCH_MM + half_wall
        y = row * CELL_PITCH_MM + half_wall
        w = length * CELL_PITCH_MM - WALL_THICKNESS_MM
        h = CELL_PITCH_MM - WALL_THICKNESS_MM
        pocket = Box(w, h, WALL_HEIGHT_MM + 0.2, align=BOTTOM)
        channel = _fuse(channel - Pos(x, y, -0.1) * pocket)

    # Subtract a 1-cell pocket for each filler. Walls around fillers are
    # shared with adjacent word pockets — also 2 mm thick.
    for row, col in filler_cells:
        x = col * CELL_PITCH_MM + half_wall
        y = row * CELL_PITCH_MM + half_wall
        s = CELL_PITCH_MM - WALL_THICKNESS_MM
        pocket = Box(s, s, WALL_HEIGHT_MM + 0.2, align=BOTTOM)
        channel = _fuse(channel - Pos(x, y, -0.1) * pocket)

    # ─── Pin shrouds (see docstring) ────────────────────────────
    # Pocket id per cell — a wall exists between two cells iff they
    # belong to different pockets. Every horizontal grid line is a wall
    # (pockets are one row tall); vertical lines are walls only at word
    # boundaries. Lines 0 and 13 are the 1 mm envelope-edge skins.
    pocket_id = {}
    for i, (row, col, length) in enumerate(spans):
        for c in range(col, col + length):
            pocket_id[(row, c)] = i
    for j, cell in enumerate(filler_cells):
        pocket_id[cell] = len(spans) + j

    def needs_shroud(px: float, py: float, reach: float) -> bool:
        """True iff this pad's cavity would eat clear THROUGH an interior
        wall. A cavity that only partially penetrates a wall leaves a
        ≥ MIN_WALL_SKIN_MM skin on the far side — a light-tight dent (the
        universal cavity subtraction below produces it); no pillar needed.
        """
        row = min(max(int(py // CELL_PITCH_MM), 0), 12)
        for k in range(1, 13):
            line = k * CELL_PITCH_MM
            for center, wall_here in (
                (px, pocket_id.get((row, k - 1)) != pocket_id.get((row, k))),
                (py, True),  # every horizontal line is a wall
            ):
                if not wall_here:
                    continue
                c0, c1 = center - reach, center + reach
                b0, b1 = line - half_wall, line + half_wall
                if c1 <= b0 or c0 >= b1:
                    continue  # no overlap with this wall band
                left_skin = c0 - b0
                right_skin = b1 - c1
                if max(left_skin, right_skin) < MIN_WALL_SKIN_MM:
                    return True
        return False

    pads = []
    with THT_PADS_CSV.open() as f:
        for rec in csv.DictReader(f):
            pads.append((rec["ref"], rec["pad"],
                         float(rec["x_mm"]), float(rec["y_mm"]),
                         float(rec["pad_size_mm"])))
    leds = []
    with LED_POS_CSV.open() as f:
        for rec in csv.DictReader(f):
            leds.append((rec["ref"], float(rec["x_mm"]), float(rec["y_mm"])))

    def led_gap(px: float, py: float, half_pillar: float) -> float:
        return min(
            max(abs(px - lx), abs(py - ly)) - (half_pillar + LED_HALF_MM)
            for _, lx, ly in leds
        )

    def rect_led_gap(x0: float, y0: float, x1: float, y1: float) -> float:
        """Smallest separation between the rect and any LED package
        (negative = overlap)."""
        worst = 1e9
        for _, lx, ly in leds:
            gx = max(x0 - (lx + LED_HALF_MM), (lx - LED_HALF_MM) - x1)
            gy = max(y0 - (ly + LED_HALF_MM), (ly - LED_HALF_MM) - y1)
            worst = min(worst, max(gx, gy))
        return worst

    channel = _fuse(channel)

    # ─── Relief rects: pure voids, nothing added at full pocket depth ──
    # One rect per pad (pad + margin); one merged rect per daughtercard
    # header row (bent-flat socket tails spread along the row).
    rects = []  # (x0, y0, x1, y1, label)
    for row_ref in HEADER_ROWS:
        row = [(px, py, ps) for ref, num, px, py, ps in pads
               if ref == row_ref and num != "npth"]
        sm = SLOT_MARGINS_MM[row_ref]
        bx0 = min(px - ps / 2 for px, py, ps in row) - sm
        bx1 = max(px + ps / 2 for px, py, ps in row) + sm
        by0 = min(py - ps / 2 for px, py, ps in row) - sm
        by1 = max(py + ps / 2 for px, py, ps in row) + sm
        rects.append((bx0, by0, bx1, by1, row_ref))
    for ref, num, px, py, ps in pads:
        if num == "npth":
            continue  # empty mounting holes: nothing protrudes, no relief
        if ref in HEADER_ROWS:
            continue  # inside that row's slot rect
        r = ps / 2 + CAVITY_MARGIN_MM
        rects.append((px - r, py - r, px + r, py + r, f"{ref}.{num}"))

    # ─── Wall jogs: route walls AROUND pins, below pin height only ──
    # Where a relief rect eats through a wall band (leaves < MIN_SKIN on
    # both sides), the wall gets a JOG: a 2 mm rib, JOG_HEIGHT_MM tall,
    # detouring around the relief on the clear side, closed back to the
    # straight wall with two end stubs. Above JOG_HEIGHT the original
    # straight wall is untouched — from the letters' perspective the
    # lattice is unchanged except thin low ribs near the PCB.
    def wall_exists_v(k: int, y: float) -> bool:
        row = min(max(int(y // CELL_PITCH_MM), 0), 12)
        return pocket_id.get((row, k - 1)) != pocket_id.get((row, k))

    jog_boxes = []      # (x0, y0, x1, y1) ribs to add at JOG_HEIGHT
    bridges = []        # un-joggable crossings to close with bridge blocks
    jogs = 0

    for axis in ("h", "v"):
        for k in range(1, 13):
            line = k * CELL_PITCH_MM
            b0, b1 = line - half_wall, line + half_wall
            # collect invading rects on this line (along, cross extents)
            invaders = []
            for (x0, y0, x1, y1, label) in rects:
                if axis == "h":
                    c0, c1, a0, a1 = y0, y1, x0, x1
                    mid = (y0 + y1) / 2
                    wall_here = True
                else:
                    c0, c1, a0, a1 = x0, x1, y0, y1
                    if not wall_exists_v(k, (y0 + y1) / 2):
                        continue
                    wall_here = True
                if c1 <= b0 or c0 >= b1:
                    continue
                if max(c0 - b0, b1 - c1) >= MIN_WALL_SKIN_MM:
                    continue  # partial bite — light-tight dent, no jog
                invaders.append((a0, a1, c0, c1, label))
            if not invaders:
                continue
            # merge invaders into clusters along the wall
            invaders.sort()
            clusters = [list(invaders[0])[:4] + [[invaders[0][4]]]]
            for a0, a1, c0, c1, label in invaders[1:]:
                if a0 <= clusters[-1][1] + 2.0:
                    clusters[-1][1] = max(clusters[-1][1], a1)
                    clusters[-1][2] = min(clusters[-1][2], c0)
                    clusters[-1][3] = max(clusters[-1][3], c1)
                    clusters[-1][4].append(label)
                else:
                    clusters.append([a0, a1, c0, c1, [label]])
            for a0, a1, c0, c1, labels in clusters:
                placed = False
                # try both sides, nearest first
                sides = sorted((( -1, line - c0), (1, c1 - line)),
                               key=lambda s: s[1])
                for sign, _ in sides:
                    if sign < 0:
                        j0, j1 = c0 - WALL_THICKNESS_MM - 0.1, c0 - 0.1
                    else:
                        j0, j1 = c1 + 0.1, c1 + WALL_THICKNESS_MM + 0.1
                    # rib + two end stubs
                    if axis == "h":
                        rib = (a0 - WALL_THICKNESS_MM, j0,
                               a1 + WALL_THICKNESS_MM, j1)
                        stub_a = (a0 - WALL_THICKNESS_MM, min(j0, b0),
                                  a0, max(j1, b1))
                        stub_b = (a1, min(j0, b0),
                                  a1 + WALL_THICKNESS_MM, max(j1, b1))
                    else:
                        rib = (j0, a0 - WALL_THICKNESS_MM,
                               j1, a1 + WALL_THICKNESS_MM)
                        stub_a = (min(j0, b0), a0 - WALL_THICKNESS_MM,
                                  max(j1, b1), a0)
                        stub_b = (min(j0, b0), a1,
                                  max(j1, b1), a1 + WALL_THICKNESS_MM)
                    boxes = [rib, stub_a, stub_b]
                    # hard constraints: clear of every LED package and of
                    # every relief rect; stay inside the envelope
                    ok = all(rect_led_gap(*bx) >= LED_MIN_GAP_MM
                             for bx in boxes)
                    if ok:
                        for bx in boxes:
                            for (rx0, ry0, rx1, ry1, _l) in rects:
                                if (bx[0] < rx1 and bx[2] > rx0
                                        and bx[1] < ry1 and bx[3] > ry0):
                                    ok = False
                                    break
                            if not ok:
                                break
                    if ok:
                        # clamp to the envelope — a rib clipped at the
                        # board edge just opens toward the frame gap,
                        # which the walnut absorbs
                        for bx in boxes:
                            jog_boxes.append((
                                max(bx[0], 0.0), max(bx[1], 0.0),
                                min(bx[2], GRID_SIZE_MM),
                                min(bx[3], GRID_SIZE_MM)))
                        jogs += 1
                        placed = True
                        break
                if not placed:
                    bridges.append((axis, k, a0, a1, c0, c1, ",".join(labels)))

    for (x0, y0, x1, y1) in jog_boxes:
        if x1 - x0 < 0.2 or y1 - y0 < 0.2:
            continue  # fully clipped by the envelope
        rib = Box(x1 - x0, y1 - y0, JOG_HEIGHT_MM, align=BOTTOM)
        channel = _fuse(channel + Pos(x0, y0, 0) * rib)

    # Subtract every relief rect as a pure void (full CAVITY_DEPTH).
    for (x0, y0, x1, y1, _label) in rects:
        cavity = Box(x1 - x0, y1 - y0, CAVITY_DEPTH_MM + 0.1, align=BOTTOM)
        channel = _fuse(channel - Pos(x0, y0, -0.1) * cavity)

    # ─── Bridges: close the un-joggable crossings (pin fences) ──────
    # Where a pin row crosses a wall mid-column, no thin wall can route
    # around it. Instead the crossing is CLOSED: two legs drop to the
    # PCB in the clear strips flanking the pin line (pins + solder are
    # ~2.6 mm wide in a ~4.4 mm trench), and a roof bridges over the
    # pins (they are <4 mm tall). The only remaining apertures are two
    # keyholes the width of the pin line itself, facing each other
    # inside a closed black box — no open notch in any wall face.
    for axis, k, a0, a1, c0, c1, labels in bridges:
        line = k * CELL_PITCH_MM
        e0 = line - half_wall - BRIDGE_OVERHANG_MM
        e1 = line + half_wall + BRIDGE_OVERHANG_MM
        if axis == "h":
            parts = [
                (a0, e0, a0 + BRIDGE_LEG_MM, e1, 0.0),          # leg
                (a1 - BRIDGE_LEG_MM, e0, a1, e1, 0.0),          # leg
                (a0, e0, a1, e1, BRIDGE_CLEAR_MM),              # roof
            ]
        else:
            parts = [
                (e0, a0, e1, a0 + BRIDGE_LEG_MM, 0.0),
                (e0, a1 - BRIDGE_LEG_MM, e1, a1, 0.0),
                (e0, a0, e1, a1, BRIDGE_CLEAR_MM),
            ]
        ok = all(rect_led_gap(x0, y0, x1, y1) >= LED_MIN_GAP_MM
                 for (x0, y0, x1, y1, _z) in parts)
        if not ok:
            raise AssertionError(
                f"bridge at {axis}-wall {k} ({labels}) would touch an LED")
        for (x0, y0, x1, y1, z0) in parts:
            box = Box(x1 - x0, y1 - y0, BRIDGE_TOP_MM - z0, align=BOTTOM)
            channel = _fuse(channel + Pos(x0, y0, z0) * box)
        print(f"  bridge: {axis}-wall {k} crossing closed over {labels}")

    # Trim anything (pillar corners near the perimeter) back to the
    # envelope so the channel still drops into the frame interior.
    envelope = Box(GRID_SIZE_MM, GRID_SIZE_MM, WALL_HEIGHT_MM, align=BOTTOM)
    channel = _fuse(channel & envelope)

    # Orientation marker: 45° chamfer on the (0,0) exterior corner — the
    # D1 / "IT IS" top-left corner of the board. The part has four
    # plausible orientations and the ESP32 pin columns are nearly
    # symmetric about board center, so a 180°-rotated placement looks
    # deceptively correct. Rule: CHAMFERED CORNER GOES TO THE D1 CORNER.
    ch = 5.0
    # Reinforce first: without this, the chamfered corner survives only
    # via the two 1 mm envelope-edge skins and prints barely attached
    # (observed on the first full print). A rib PARALLEL to the chamfer
    # face ties both skins together into a solid corner; the diamond cut
    # afterwards leaves a crisp face.
    rib = Pos(2.2, 2.2, 0) * Rot(Z=-45) * Box(
        9.0, 2.0, WALL_HEIGHT_MM,
        align=(Align.CENTER, Align.CENTER, Align.MIN))
    channel = _fuse(channel + rib)
    diamond = Pos(0, 0, -0.1) * Rot(Z=45) * Box(
        ch, ch, WALL_HEIGHT_MM + 0.2,
        align=(Align.CENTER, Align.CENTER, Align.MIN))
    channel = _fuse(channel - diamond)
    # The rib's ends extend past the outer faces — trim back to the
    # envelope so the part keeps its exact 177.8 mm square.
    channel = _fuse(channel & Box(GRID_SIZE_MM, GRID_SIZE_MM,
                                  WALL_HEIGHT_MM, align=BOTTOM))

    return channel, len(spans), len(filler_cells), jogs



def to_physical(shape):
    """KiCad's internal frame is y-down (left-handed vs the physical front
    view); this model builds in those coordinates, so the solid must be
    MIRRORED about the y midline before export or every feature lands on
    the wrong side of the physical board. KiCad's own fab exports negate
    y for exactly this reason (see word-clock.drl). Discovered after four
    mirrored prints — do not remove."""
    return _fuse(Pos(0, GRID_SIZE_MM, 0) * mirror(shape, about=Plane.XZ))


def export_main_solid(shape, path: str) -> None:
    """Export the largest solid; boolean chains can shed tiny orphan
    slivers (e.g. a wall corner fully surrounded by cuts) that would
    otherwise make export fail or print as loose dust."""
    items = list(shape) if isinstance(shape, (list, tuple)) else [shape]
    solids = sorted((s for it in items for s in it.solids()),
                    key=lambda s: s.volume, reverse=True)
    dropped = sum(s.volume for s in solids[1:])
    if dropped > 100.0:
        raise AssertionError(
            f"part split into large disconnected bodies "
            f"({dropped:.0f} mm³ outside the main solid) — geometry bug")
    if len(solids) > 1:
        print(f"  note: dropped {len(solids) - 1} orphan sliver(s), "
              f"{dropped:.1f} mm³ total")
    export_stl(solids[0], path)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--target", choices=["emory", "nora"], required=True)
    parser.add_argument(
        "--coupon", action="store_true",
        help="export only a 7 mm-tall crop of the densest pin region "
             "(U1 shroud columns + J_RTC dent row) as a ~40 min fit-check "
             "print before committing to the full part")
    args = parser.parse_args()

    channel, n_words, n_fillers, n_jogs = build_channel(args.target)

    out_dir = Path(__file__).parent / "out"
    out_dir.mkdir(exist_ok=True)
    if args.coupon:
        BOTTOM = (Align.MIN, Align.MIN, Align.MIN)
        # cols 1-7 (v1..v8) x rows 2-8: SD row + both U1 pin columns +
        # J_RTC row — every region that has ever failed a dry-fit
        x0, x1 = 1 * CELL_PITCH_MM, 8 * CELL_PITCH_MM
        y0, y1 = 2 * CELL_PITCH_MM, 9 * CELL_PITCH_MM
        window = (Pos(x0, y0, 0)
                  * Box(x1 - x0, y1 - y0, JOG_HEIGHT_MM + 2.0,
                        align=BOTTOM))
        channel = _fuse(channel & window)
        # Coupon orientation marker (additive — a cut would sever the
        # thin cropped walls at this corner): a small tab pointing
        # toward the board's D1 (top-left) corner, same rule as the full
        # part's chamfer.
        tab = Pos(x0 - 4.0, y0 - 4.0, 0) * Box(8.0, 8.0, 3.0, align=BOTTOM)
        channel = _fuse(channel + tab)
        stl_path = out_dir / f"light_channel_coupon_{args.target}.stl"
        export_main_solid(to_physical(channel), str(stl_path))
        print(f"wrote {stl_path} (fit-check coupon: x {x0:.1f}-{x1:.1f}, "
              f"y {y0:.1f}-{y1:.1f}, {JOG_HEIGHT_MM + 2.0:.0f} mm tall)")
        print("Dry-fit it over the U1/J_RTC pin field: every stub should "
              "disappear into a cavity and the wall edges should sit flat "
              "on the PCB surface.")
        return
    stl_path = out_dir / f"light_channel_{args.target}.stl"
    export_main_solid(to_physical(channel), str(stl_path))

    print(f"wrote {stl_path}")
    print(f"  target:           {args.target}")
    print(f"  envelope:         {GRID_SIZE_MM:.2f} × {GRID_SIZE_MM:.2f} × {WALL_HEIGHT_MM:.2f} mm")
    print(f"  cell pitch:       {CELL_PITCH_MM:.4f} mm")
    print(f"  wall thickness:   {WALL_THICKNESS_MM:.1f} mm")
    print(f"  word pockets:     {n_words}")
    print(f"  filler pockets:   {n_fillers}")
    print(f"  total pockets:    {n_words + n_fillers}")
    print(f"  wall jogs:        {n_jogs} (ribs {JOG_HEIGHT_MM:.1f} mm tall; "
          f"cavities {CAVITY_DEPTH_MM:.1f} mm deep)")


if __name__ == "__main__":
    main()
